all:
  hosts:
    oci:
      ansible_host: oci02vbld11.dhsie.hawaii.gov
      ansible_connection: ssh
      app_url: "https://build-oci.dhsie.hawaii.gov"
     
    nonprod:
      ansible_host: npd02vbld11.dhsie.hawaii.gov
      ansible_connection: ssh
      app_url: "https://build-nonp.dhsie.hawaii.gov"

    prod:
      ansible_host: prd02vbld11.dhsie.hawaii.gov
      ansible_connection: ssh
      app_url: "https://build.dhsie.hawaii.gov"
