all:
  hosts:
    nonprod:
      ansible_host: orel9
      ansible_connection: ssh
      app_url: "https://cgw01v"

    prod:
      ansible_host: ses01
      ansible_connection: ssh
      app_url: "https://bses01"

